! defines a variable with value of 5:
THIS x IS 5
! prints value of x (5):
THINGSAY x
! prints "Hello ThingLang!":
THINGSAY "Hello ThingLang!"

! creates a function named greet:
DOTHING greet GONNA
! prints "Hello from a function!":
    THINGSAY "Hello from a function!"
! ends the function part:
GONNAEND

! calls the function:
greet

! starts a loop:
NOTAGAIN
! prints "Looping...":
    THINGSAY "Looping..."
! tells the loop to do the part n times:
TIMES IS 3
